name: myapp
description: "Proyecti final Nagua."
publish_to: 'Leonardo Emil Amparo' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  flutter_lints: ^3.0.0
  quickalert: ^1.1.0
  loading_animation_widget: ^1.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/ember.png
    - assets/images/zao.png
    - assets/images/grappa.png
    - assets/images/larimar.png

  uses-material-design: true
